# Generated by Django 6.0.7 on 2026-08-03 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proje',
            options={'verbose_name': 'Proje (Sipariş)', 'verbose_name_plural': '5. Projeler ve Siparişler'},
        ),
        migrations.AddField(
            model_name='proje',
            name='durum',
            field=models.CharField(choices=[('teklif', '📝 Teklif Aşaması'), ('uretim', '🏭 Atölyede / Üretimde'), ('montaj', '🚛 Montaj / Sevkiyatta'), ('teslim', '✅ Teslim Edildi')], default='teklif', max_length=20),
        ),
        migrations.AddField(
            model_name='proje',
            name='iban_bilgisi',
            field=models.CharField(blank=True, help_text='Fatura için kurumsal IBAN', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='proje',
            name='notlar',
            field=models.TextField(blank=True, help_text='Müşteriye özel veya siparişe özel notlar', null=True),
        ),
    ]
