# Generated by Django 6.0.7 on 2026-08-03 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_proje_options_proje_durum_proje_iban_bilgisi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proje',
            name='durum',
            field=models.CharField(choices=[('teklif', '📝 Teklif Verildi / Onay Bekliyor'), ('kapora', '💵 Kapora / Ödeme Alındı'), ('olcu', '📐 Ölçü Bekleniyor / Kontrol Edilecek'), ('uretim', '🏭 Atölyede / İmalatta'), ('montaj', '🚛 Montaja Hazır / Sevkiyatta'), ('teslim', '✅ Montaj Tamamlandı & Teslim Edildi')], default='teklif', max_length=20),
        ),
    ]
