# Generated by Django 6.0.7 on 2026-08-04 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_proje_durum'),
    ]

    operations = [
        migrations.AddField(
            model_name='firma',
            name='abonelik_aktif',
            field=models.BooleanField(default=False, verbose_name='Ödemeli Abonelik Aktif Mi?'),
        ),
        migrations.AlterField(
            model_name='firma',
            name='abonelik_baslangic',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Abonelik/Kayıt Başlangıç'),
        ),
    ]
