# Generated by Django 6.0.7 on 2026-08-10 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_firma_abonelik_aktif_alter_firma_abonelik_baslangic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='firma',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='calisanlar', to='users.firma', verbose_name='Bağlı Olduğu Firma'),
            preserve_default=False,
        ),
    ]
