# Generated by Django 6.0.7 on 2026-08-11 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_firma'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='rol',
            field=models.CharField(choices=[('patron', 'Patron'), ('usta', 'Usta')], default='usta', max_length=10, verbose_name='Rol'),
        ),
    ]
