# Generated by Django 6.0.7 on 2026-08-11 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_set_rol_from_firma_sahibi_mi'),
    ]

    operations = [
        migrations.AddField(
            model_name='firma',
            name='abonelik_donduruldu',
            field=models.BooleanField(default=False, verbose_name='Abonelik Donduruldu Mu?'),
        ),
        migrations.AddField(
            model_name='firma',
            name='dondurma_tarihi',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Dondurma Tarihi'),
        ),
    ]
