# Generated by Django 6.0.7 on 2026-08-12 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_firma_abonelik_donduruldu_firma_dondurma_tarihi'),
    ]

    operations = [
        migrations.CreateModel(
            name='HesapSilmeTalebi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='E-posta Adresi')),
                ('aciklama', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Talep Tarihi')),
                ('islendi_mi', models.BooleanField(default=False, verbose_name='İşlendi Mi?')),
            ],
            options={
                'verbose_name': 'Hesap Silme Talebi',
                'verbose_name_plural': '6. Hesap Silme Talepleri',
            },
        ),
    ]
