# Generated by Django 6.0.7 on 2026-08-16 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_create_default_paketler'),
    ]

    operations = [
        migrations.AddField(
            model_name='firma',
            name='abonelik_periyot',
            field=models.CharField(blank=True, choices=[('aylik', 'Aylık'), ('yillik', 'Yıllık'), ('tek_seferlik', 'Tek Seferlik')], max_length=15, null=True, verbose_name='Abonelik Periyodu'),
        ),
    ]
