# Generated by Django 6.0.7 on 2026-08-16 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_firma_abonelik_periyot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonelikpaketi',
            name='periyot',
            field=models.CharField(choices=[('Aylık', 'Aylık'), ('Yıllık', 'Yıllık'), ('tek_seferlik', 'Tek Seferlik')], default='Aylık', max_length=15, verbose_name='Ödeme Periyodu'),
        ),
    ]
